import "./styles.css";
import React, { useState } from "react";

var emojiDictionary = {
  "😀": "Grinning",
  "😃": "Wide-Eyed",
  "😄": "Smiling",
  "😁": "Beaming",
  "😆": "Squinting",
  "😅": "Sweating",
  "🤣": "Laughing",
  "😂": "Joyful",
  "🙂": "Slight",
  "😉": "Winking",
  "😊": "Happy",
  "😇": "Haloed",
  "🥰": "Lovestruck",
  "😍": "Heart-Eyed",
  "🤩": "Star-Struck",
  "😘": "Kissing",
  "😗": "Kiss",
  "☺": "Smile",
  "😚": "Affectionate",
  "😙": "Tender",
  "🥲": "Tearful",
  "😏": "Smirking",
  "😋": "Savoring",
  "😛": "Playful",
  "😜": "Winking-Tongue",
  "🤪": "Zany",
  "😝": "Squinting-Tongue",
  "🤗": "Hugging",
  "🤭": "Giggling",
  "🫢": "Disguised",
  "🫣": "Veiled",
  "🤫": "Shushing",
  "🤔": "Thinking",
  "🫡": "Pondering",
  "🤤": "Savoring",
  "🤠": "Cowboy",
  "🥳": "Celebrating",
  "🥸": "Disguised",
  "😎": "Cool",
  "🤓": "Nerdy",
  "🧐": "Examining",
  "🙃": "Upside-Down",
  "🫠": "Unwell",
  "🤐": "Silent",
  "🤨": "Puzzled",
  "😐": "Neutral",
  "😑": "Expressionless",
  "😶": "Muted",
  "🫥": "Anxious",
  "😶‍🌫️‍‍": "Hushed",
  "😒": "Unamused",
  "🙄": "Exasperated",
  "😬": "Grimacing",
  "😮‍💨": "Surprised-Exhaling",
  "🤥": "Lying",
  "🫨": "Dizzy",
  "😌": "Relieved",
  "😔": "Disappointed",
  "😪": "Sleepy",
  "😴": "Sleeping",
  "😷": "Masked",
  "🤒": "Sick",
  "🤕": "Injured",
  "🤢": "Nauseated",
  "🤮": "Vomiting",
  "🤧": "Sneezing",
  "🥵": "Overheated",
  "🥶": "Cold",
  "🥴": "Dizzy-Face",
  "😵": "Dizzy",
  "😵‍💫": "Star-Struck",
  "🤯": "Mind-Blown",
  "🥱": "Yawning",
  "😕": "Confused",
  "🫤": "Dejected",
  "😟": "Worried",
  "🙁": "Frowning",
  "☹": "Frown",
  "😮": "Astonished",
  "😯": "Aghast",
  "😲": "Astonished",
  "😳": "Flustered",
  "🥺": "Pleading",
  "🥹": "Injured",
  "😦": "Frowning",
  "😧": "Anguished",
  "😨": "Fearful",
  "😰": "Anxious",
  "😥": "Disappointed",
  "😢": "Sad",
  "😭": "Crying",
  "😱": "Terrified",
  "😖": "Annoyed",
  "😣": "Persevering",
  "😞": "Dissatisfied",
  "😓": "Sweat",
  "😩": "Weary",
  "😫": "Tired",
  "😤": "Steam from Nose",
  "😡": "Angry",
  "😠": "Angry",
  "🤬": "Cursing",
  "👿": "Angry",
  "😈": "Impish",
  "👿": "Evil",
  "💀": "Skull",
  "☠️": "Skull and Crossbones",
  "💩": "Poop",
  "🤡": "Clown",
  "👹": "Ogre",
  "👺": "Goblin",
  "👻": "Ghost",
  "👽": "Alien",
  "👾": "Alien Monster",
  "🤖": "Robot",
  "😺": "Grinning Cat",
  "😸": "Grinning Cat with Smiling Eyes",
  "😹": "Cat with Tears of Joy",
  "😻": "Smiling Cat with Heart Eyes",
  "😼": "Smirking Cat",
  "😽": "Kissing Cat",
  "🙀": "Weary Cat",
  "😿": "Crying Cat",
  "😾": "Pouting Cat",
  "🙈": "See-No-Evil Monkey",
  "🙉": "Hear-No-Evil Monkey",
  "🙊": "Speak-No-Evil Monkey"
};

export default function App() {
  var [input, setMeaning] = useState("");
  function emojiUserInputHandler(event) {
    var userInput = event.target.value;
    var meaning = emojiDictionary[userInput];
    setMeaning(meaning);
  }

  return (
    <div className="App">
      <h1>Emoji Meaning Finder</h1>
      <input onChange={emojiUserInputHandler} />
      <div> {input} </div>
    </div>
  );
}
